on: push

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        env:
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        run: |
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .env
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cats
          path: .env
